### Data Transformation

In [2]:
#Importing Libraries and loading data sets
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
df = pd.read_excel('Data Migration.xlsx')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  
0        101348.88  
1        112542.58  
2        113931.57  
3         93826.63  
4         79084.10

we see that the estimated salary and balance does not have a currency symbol so we would be adding that.

In [3]:
###Overview of Data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
dtypes: float64(2), int64(8), object(3)
memory usage: 1015.8+ KB


In [4]:
from babel.numbers import format_currency

In [5]:
df['Balance'] = df['Balance'].apply(lambda x: format_currency(x, currency = 'USD', locale = "en_US"))

In [6]:
df['EstimatedSalary'] = df['EstimatedSalary'].apply(lambda x: format_currency(x, currency = 'USD', locale = "en_US"))

In [7]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure      Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2        $0.00              1          1               1   
1          1   $83,807.86              1          0               1   
2          8  $159,660.80              3          1               0   
3          1        $0.00              2          0               0   
4          2  $125,510.82              1          1               1   
...      ...          ...            ...        ...             ...   
9995       5        $0.00              2          1               0   
9996      10   $57,369.61              1          1               1   
9997       7        $0.00              1          0               1   
9998       3   $75,075.31              2          1               0   
9999       4  $130,142.79              1          1               0   

     EstimatedSalary  
0        $101,348.88  
1        $112,542.58  
2        $113,931.57  
3         $93,826.63  
4         $79,084.10  
...              ...  
9995      $96,270.64  
9996     $101,699.77  
9997      $42,085.58  
9998      $92,888.52  
9999      $38,190.78  

[10000 rows x 13 columns]

next we break the table into multiple dataframe 

In [8]:
CustomerHistory = df[['RowNumber', 'CustomerId','Surname','CreditScore','Gender','Age','Tenure','Geography','IsActiveMember',
                     'EstimatedSalary']]
CustomerHistory

RowNumber  CustomerId    Surname  CreditScore  Gender  Age  Tenure  \
0             1    15634602   Hargrave          619  Female   42       2   
1             2    15647311       Hill          608  Female   41       1   
2             3    15619304       Onio          502  Female   42       8   
3             4    15701354       Boni          699  Female   39       1   
4             5    15737888   Mitchell          850  Female   43       2   
...         ...         ...        ...          ...     ...  ...     ...   
9995       9996    15606229   Obijiaku          771    Male   39       5   
9996       9997    15569892  Johnstone          516    Male   35      10   
9997       9998    15584532        Liu          709  Female   36       7   
9998       9999    15682355  Sabbatini          772    Male   42       3   
9999      10000    15628319     Walker          792  Female   28       4   

     Geography  IsActiveMember EstimatedSalary  
0       France               1     $101,348.88  
1        Spain               1     $112,542.58  
2       France               0     $113,931.57  
3       France               0      $93,826.63  
4        Spain               1      $79,084.10  
...        ...             ...             ...  
9995    France               0      $96,270.64  
9996    France               1     $101,699.77  
9997    France               1      $42,085.58  
9998   Germany               0      $92,888.52  
9999    France               0      $38,190.78  

[10000 rows x 10 columns]

In [9]:
CustomerHistory['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [10]:
CustomerHistory['Tenure'].unique()

array([ 2,  1,  8,  7,  4,  6,  3, 10,  5,  9,  0], dtype=int64)

In [11]:
CustomerHistory['IsActiveMember'].unique()

array([1, 0], dtype=int64)

we are going to encode the text data in Geography to numerical data and then change the attribute name of Tenure to TenureId, IsActiveMember to activememberId and Geography to geographyId.

In [12]:
# replacing the Geography with 1 or 0
CustomerHistory.replace({'Geography':{'France':0, 'Spain':1, 'Germany' : 2}},inplace = True)

In [13]:
#Now we change the name of the attributes
CustomerHistory.rename(columns= {'Tenure': 'TenureId', 'IsActiveMember':'ActiveMemberId', 'Geography' : 'GeographyId'},inplace = True)

In [14]:
CustomerHistory.head()

RowNumber  CustomerId   Surname  CreditScore  Gender  Age  TenureId  \
0          1    15634602  Hargrave          619  Female   42         2   
1          2    15647311      Hill          608  Female   41         1   
2          3    15619304      Onio          502  Female   42         8   
3          4    15701354      Boni          699  Female   39         1   
4          5    15737888  Mitchell          850  Female   43         2   

   GeographyId  ActiveMemberId EstimatedSalary  
0            0               1     $101,348.88  
1            1               1     $112,542.58  
2            0               0     $113,931.57  
3            0               0      $93,826.63  
4            1               1      $79,084.10

In [15]:
#Creating Ture,IsActiveMember and Geography Table
Tenure = {
    'Id' : [0,1,2,3,4,5,6,7,8,9,10],
    'Tenure Duration': ['Half a year','1 year','2 years','3 years', '4 years','5 years',
                       '6 years','7 years','8 years', '9 years','10 years']
}
Tenure = pd.DataFrame(Tenure)
Tenure

Id Tenure Duration
0    0     Half a year
1    1          1 year
2    2         2 years
3    3         3 years
4    4         4 years
5    5         5 years
6    6         6 years
7    7         7 years
8    8         8 years
9    9         9 years
10  10        10 years

In [16]:
IsActiveMember = {
    'Id' : [0,1],
    'ActiveMember': ['Inactive','Active']
}
IsActiveMember = pd.DataFrame(IsActiveMember)
IsActiveMember

Id ActiveMember
0   0           No
1   1          Yes

In [17]:
Geography = {
    'Id' : [0,1,2],
    'Location': ['France','Spain','Germany']
}
Geography = pd.DataFrame(Geography)
Geography

Id Location
0   0   France
1   1    Spain
2   2  Germany

In [18]:
Sales = df[['CustomerId','HasCrCard','NumOfProducts','Balance']]
Sales

CustomerId  HasCrCard  NumOfProducts      Balance
0       15634602          1              1        $0.00
1       15647311          0              1   $83,807.86
2       15619304          1              3  $159,660.80
3       15701354          0              2        $0.00
4       15737888          1              1  $125,510.82
...          ...        ...            ...          ...
9995    15606229          1              2        $0.00
9996    15569892          1              1   $57,369.61
9997    15584532          0              1        $0.00
9998    15682355          1              2   $75,075.31
9999    15628319          1              1  $130,142.79

[10000 rows x 4 columns]

In [20]:
Sales['HasCrCard'].unique()

array([1, 0], dtype=int64)

we are going to make the numerical data in the Sales dataset to a text of Yes for 1 and No for 0.

In [25]:
Sales.replace({'HasCrCard':{0:'No', 1:'Yes'}},inplace = True)

In [26]:
Sales.head()

CustomerId HasCrCard  NumOfProducts      Balance
0    15634602       Yes              1        $0.00
1    15647311        No              1   $83,807.86
2    15619304       Yes              3  $159,660.80
3    15701354        No              2        $0.00
4    15737888       Yes              1  $125,510.82

In [27]:
#Changing CustomerId to just Id
Sales.rename(columns ={'CustomerId':'Id'}, inplace = True)

In [28]:
Sales.head()

Id HasCrCard  NumOfProducts      Balance
0  15634602       Yes              1        $0.00
1  15647311        No              1   $83,807.86
2  15619304       Yes              3  $159,660.80
3  15701354        No              2        $0.00
4  15737888       Yes              1  $125,510.82

In [29]:
CustomerHistory.to_csv("CustomerHistory.csv",index=False)

In [30]:
Geography.to_csv("Geography.csv",index=False)

In [31]:
Tenure.to_csv("Tenure.csv",index=False)

In [32]:
IsActiveMember.to_csv("IsActiveMember.csv",index=False)

In [33]:
Sales.to_csv("Sales.csv",index=False)